# Generated by Django 4.2.6 on 2023-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AddField(
            model_name='items',
            name='task_Id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False),
        ),
    ]
