# Generated by Django 4.2.6 on 2023-11-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_items_id_items_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='task_Id',
            field=models.IntegerField(default=1),
        ),
    ]
