# Generated by Django 4.2.6 on 2023-11-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_items_id_alter_items_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='task_Id',
        ),
    ]
